[tool.taskipy.tasks]
lint = "blue --check --diff . && isort --check --diff ."
docs = "mkdocs serve"
pre_test = "task lint"
test = "pytest -s -x --cov=minhashoras_apps -vv"
post_test = "coverage html"

[tool.blue]
exclude="igrations"

[tool.isort]
profile = "black"
line_length = 79
skip="migrations"
