# Generated by Django 4.1.7 on 2023-05-13 00:15

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_account_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator], verbose_name='email')),
                ('notes', ckeditor.fields.RichTextField(blank=True, help_text='Notes about the client.', verbose_name='notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'unique_together': {('account', 'name')},
            },
        ),
    ]
