# Generated by Django 4.1.7 on 2023-05-13 13:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_options_alter_user_options_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Description of the project', verbose_name='description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.account', verbose_name='account')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'unique_together': {('account', 'name')},
            },
        ),
    ]
