# Generated by Django 4.1.7 on 2023-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='quick_info',
            field=models.TextField(blank=True, help_text='Quick info about the client.', max_length=150, verbose_name='quick info'),
        ),
    ]
